name: TP
channels:
  - https://software.repos.intel.com/python/conda
  - conda-forge
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - biopython=1.85=py39h8cd3c5a_1
  - bzip2=1.0.8=hda65f42_8
  - ca-certificates=2025.11.12=hbd8a1cb_0
  - click=8.1.8=pyh707e725_0
  - dataclasses=0.8=pyhc8e2a94_3
  - dpcpp-cpp-rt=2025.0.4=intel_1519
  - huggingface_hub=0.34.4=pyhd8ed1ab_1
  - icu=78.1=h33c6efd_0
  - importlib-metadata=8.7.0=pyhe01879c_1
  - importlib_metadata=8.7.0=h40b2b14_1
  - intel-cmplr-lib-rt=2025.0.4=intel_1519
  - intel-cmplr-lib-ur=2025.0.4=intel_1519
  - intel-cmplr-lic-rt=2025.0.4=intel_1519
  - intel-opencl-rt=2025.0.4=intel_1519
  - intel-openmp=2025.0.4=intel_1519
  - intel-pti=0.10.2=intel_6
  - intel-sycl-rt=2025.0.4=intel_1519
  - joblib=1.5.1=pyhd8ed1ab_0
  - ld_impl_linux-64=2.45=bootstrap_ha15bf96_5
  - libabseil=20250512.1=cxx17_hba17884_0
  - libblas=3.11.0=5_h4a7cf45_openblas
  - libcblas=3.11.0=5_h0358290_openblas
  - libexpat=2.7.3=hecca717_0
  - libffi=3.5.2=h9ec8514_0
  - libgcc=15.2.0=he0feb66_16
  - libgcc-ng=15.2.0=h69a702a_16
  - libgfortran=15.2.0=h69a702a_16
  - libgfortran-ng=15.2.0=h69a702a_16
  - libgfortran5=15.2.0=h68bc16d_16
  - libgomp=15.2.0=he0feb66_16
  - liblapack=3.11.0=5_h47877c9_openblas
  - liblzma=5.8.1=hb9d3cd8_2
  - liblzma-devel=5.8.1=hb9d3cd8_2
  - libnsl=2.0.1=hb9d3cd8_1
  - libopenblas=0.3.30=pthreads_h94d23a6_4
  - libprotobuf=6.31.1=h49aed37_4
  - libsentencepiece=0.2.0=hb747028_12
  - libsqlite=3.51.1=hf4e2dac_1
  - libstdcxx=15.2.0=h934c35e_16
  - libstdcxx-ng=15.2.0=hdf11a46_16
  - libuuid=2.41.3=h5347b49_0
  - libxcrypt=4.4.36=hd590300_1
  - libzlib=1.3.1=hb9d3cd8_2
  - mkl=2025.0.1=intel_14
  - mkl-include=2025.0.1=intel_14
  - mkl-static=2025.0.1=intel_14
  - ncurses=6.5=h2d0b736_3
  - openssl=3.6.0=h26f9b46_0
  - opt-einsum=3.4.0=hd8ed1ab_1
  - opt_einsum=3.4.0=pyhd8ed1ab_1
  - optree=0.17.0=py39h8f7d636_0
  - pandas=2.3.1=py39h1b6b32d_0
  - pip=25.2=pyh8b19718_0
  - python=3.9.23=hc30ae73_0_cpython
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python-tzdata=2025.2=pyhd8ed1ab_0
  - python_abi=3.9=8_cp39
  - pytz=2025.2=pyhd8ed1ab_0
  - readline=8.3=h853b02a_0
  - sacremoses=0.0.53=pyhd8ed1ab_0
  - scikit-learn=1.6.1=py39h4b7350c_0
  - scipy=1.13.1=py39haf93ffa_0
  - sentencepiece=0.2.0=h412708c_12
  - sentencepiece-python=0.2.0=py39h6c32fdd_12
  - sentencepiece-spm=0.2.0=hb747028_12
  - setuptools=80.9.0=pyhff2d567_0
  - six=1.17.0=pyhe01879c_1
  - sqlite=3.51.1=h04a0ce9_1
  - tbb=2022.3.0=intel_381
  - tbb-devel=2022.3.0=intel_381
  - tcm=1.2.0=intel_589
  - threadpoolctl=3.6.0=pyhecae5ae_0
  - tk=8.6.13=noxft_h4845f30_101
  - typing_extensions=4.14.1=pyhe01879c_0
  - tzdata=2025c=h8577fbf_0
  - umf=0.9.1=intel_6
  - wheel=0.45.1=pyhd8ed1ab_1
  - xz=5.8.1=hbcc6ac9_2
  - xz-gpl-tools=5.8.1=hbcc6ac9_2
  - xz-tools=5.8.1=hb9d3cd8_2
  - zipp=3.23.0=pyhd8ed1ab_0
  - zlib=1.3.1=hb9d3cd8_2
  - pip:
      - captum==0.8.0
      - certifi==2025.11.12
      - charset-normalizer==3.4.4
      - contourpy==1.3.0
      - cycler==0.12.1
      - et-xmlfile==2.0.0
      - filelock==3.19.1
      - fonttools==4.60.2
      - fsspec==2025.10.0
      - hf-xet==1.2.0
      - huggingface-hub==0.36.0
      - idna==3.11
      - importlib-resources==6.5.2
      - jinja2==3.1.6
      - kiwisolver==1.4.7
      - markupsafe==3.0.3
      - matplotlib==3.9.4
      - mpmath==1.3.0
      - networkx==3.2.1
      - numpy==1.26.4
      - nvidia-cublas-cu12==12.4.5.8
      - nvidia-cuda-cupti-cu12==12.4.127
      - nvidia-cuda-nvrtc-cu12==12.4.127
      - nvidia-cuda-runtime-cu12==12.4.127
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.2.1.3
      - nvidia-curand-cu12==10.3.5.147
      - nvidia-cusolver-cu12==11.6.1.9
      - nvidia-cusparse-cu12==12.3.1.170
      - nvidia-cusparselt-cu12==0.6.2
      - nvidia-nccl-cu12==2.21.5
      - nvidia-nvjitlink-cu12==12.4.127
      - nvidia-nvtx-cu12==12.4.127
      - openpyxl==3.1.5
      - packaging==25.0
      - pillow==11.3.0
      - protobuf==6.33.2
      - pyparsing==3.3.1
      - pyyaml==6.0.3
      - regex==2025.11.3
      - requests==2.32.5
      - safetensors==0.7.0
      - seaborn==0.13.2
      - sympy==1.13.1
      - tokenizers==0.22.1
#      - torch==2.6.0+cu124
#      - torchaudio==2.6.0+cu124
#      - torchvision==0.21.0+cu124
      - tqdm==4.67.1
      - transformers==4.57.3
      - triton==3.2.0
      - typing-extensions==4.15.0
      - urllib3==2.6.2
